# Generated by Django 6.1.1 on 2026-10-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_mmo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="character",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_character_name_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="character",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__gte", 1), ("level__lte", 60)),
                name="character_level_between_1_and_60",
            ),
        ),
    ]
