# Generated by Django 6.1.1 on 2026-10-02 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_mmo", "0002_character_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="specializations",
            new_name="specialization",
        ),
        migrations.AddField(
            model_name="character",
            name="specialization",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="cyberpunk_mmo.specialization",
            ),
            preserve_default=False,
        ),
    ]
