# Generated by Django 6.1.1 on 2026-10-02 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_mmo", "0003_rename_specializations_skill_specialization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="specialization",
            field=models.ForeignKey(
                default="Gunslinger",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="cyberpunk_mmo.specialization",
            ),
        ),
    ]
