# Generated by Django 6.1.1 on 2026-10-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_mmo", "0005_alter_character_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="cyberpunk_mmo.specialization",
            ),
        ),
    ]
