# Generated by Django 6.1.1 on 2026-10-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_mmo", "0006_alter_character_specialization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faction",
            options={"ordering": ["name"]},
        ),
    ]
