# Generated by Django 6.1.1 on 2026-10-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_mmo", "0008_post_alter_specialization_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
