# Generated by Django 6.1.1 on 2026-10-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_mmo", "0009_alter_character_options_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="male",
                max_length=7,
            ),
        ),
    ]
