# Generated by Django 6.1.1 on 2026-10-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyberpunk_mmo", "0010_character_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=7,
            ),
        ),
    ]
